inputs:

  kubernetes_server_binary:
    default: https://dl.k8s.io/v1.6.6/kubernetes-server-linux-amd64.tar.gz

node_types:

  cloudify.nodes.CloudConfig:
    derived_from: cloudify.nodes.Root
    properties:
      encode_base64:
        default: false
      resource_config:
        required: False
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: scripts/cloud_config/create.py
          executor: central_deployment_agent
        configure:
          implementation: scripts/cloud_config/configure.py
          executor: central_deployment_agent
          inputs:
            resource_config:
              default:
                preserve_hostname: false
                manage_etc_hosts: true
                hostname: { get_attribute: [ SELF, node_instance_id ] }
                fqdn: { get_attribute: [ SELF, node_instance_id ] }

node_templates:

  master_cloud_config:
    type: cloudify.nodes.CloudConfig
    properties:
      resource_config:
        bootcmd:
          - mkdir -p /srv/{salt/{base,bin,kube-apiserver,kubelet},pillar,reactor/kubernetes}
          - mkdir -p /tmp/kubernetes/source
        users: &cloud_config_users
          - name: { get_input: agent_user }
            primary-group: wheel
            shell: /bin/bash
            sudo: ['ALL=(ALL) NOPASSWD:ALL']
            ssh-authorized-keys:
              - { get_secret: agent_key_public }
        write_files:
#          - path: /etc/yum.repos.d/kubernetes.repo
#            owner: root:root
#            permissions: '0444'
#            content: |
#              # installed by cloud-init
#              [kubernetes]
#              name=Kubernetes
#              baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
#              enabled=1
#              gpgcheck=1
#              repo_gpgcheck=1
#              gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
#                     https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
          - path: /etc/yum.repos.d/saltstack.repo
            owner: root:root
            permissions: '0444'
            content: |
              # installed by cloud-init
              [saltstack-repo]
              name=SaltStack repo for Red Hat Enterprise Linux $releasever
              baseurl=https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest
              enabled=1
              gpgcheck=1
              gpgkey=https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest/SALTSTACK-GPG-KEY.pub
                     https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest/base/RPM-GPG-KEY-CentOS-7
        packages: &cloud_config_packages
#          - [docker, 1.12.6-28.git1398f24.el7.centos]
          - salt-master
          - salt-minion
          - salt-ssh
          - salt-syndic
          - salt-cloud
        runcmd:
          - setenforce 0
          - systemctl disable iptables-services firewalld
          - systemctl stop iptables-services firewalld
          - [ systemctl, enable, salt-master.service ]
          - [ systemctl, start, salt-master.service ]
#          - [ systemctl, enable, docker.service ]
#          - [ systemctl, start, docker.service ]
          - { concat: [ 'curl -L ', { get_input: kubernetes_server_binary }, '| tar zx -C /tmp' ] }
          - tar xzvf /tmp/kubernetes/kubernetes-src.tar.gz -C /tmp/kubernetes/source/
          - cp -R /tmp/kubernetes/server/bin/* /srv/salt/bin
          - cp -R /tmp/kubernetes/source/cluster/saltbase/salt/* /srv/salt/
          - cp -R /tmp/kubernetes/source/cluster/saltbase/pillar/* /srv/pillar/
          - cp -R /tmp/kubernetes/source/cluster/saltbase/reactor/* /srv/reactor/kubernetes/
          - sed -i -- s/#kube-apiserver_docker_tag_value#/$(</srv/salt/bin/kube-apiserver.docker_tag)/g /srv/pillar/docker-images.sls
          - sed -i -- s/#kube-controller-manager_docker_tag_value#/$(</srv/salt/bin/kube-controller-manager.docker_tag)/g /srv/pillar/docker-images.sls
          - sed -i -- s/#kube-scheduler_docker_tag_value#/$(</srv/salt/bin/kube-scheduler.docker_tag)/g /srv/pillar/docker-images.sls
          - sed -i -- s/#kube-proxy_docker_tag_value#/$(</srv/salt/bin/kube-proxy.docker_tag)/g /srv/pillar/docker-images.sls
          - |
            cat <<EOF >/srv/pillar/cluster-params.sls
            allocate_node_cidrs: "true"
            service_cluster_ip_range: 10.244.0.0/14
            cert_ip: 10.244.0.1
            enable_cluster_monitoring: influxdb
            enable_cluster_logging: "true"
            enable_cluster_ui: "true"
            enable_node_logging: "true"
            logging_destination: elasticsearch
            elasticsearch_replicas: "1"
            enable_cluster_dns: "true"
            dns_server: 10.244.0.10
            dns_domain: cluster.local
            enable_dns_horizontal_autoscaler: "false"
            instance_prefix: kubernetes
            admission_control: Initializers,NamespaceLifecycle,LimitRanger,SecurityContextDeny,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,ResourceQuota
            enable_cpu_cfs_quota: "true"
            network_provider: none
            cluster_cidr: "10.246.0.0/16"
            e2e_storage_test_environment: "false"
            EOF


  minion_cloud_config:
    type: cloudify.nodes.CloudConfig
    properties:
      resource_config:
        users: *cloud_config_users
        write_files:
          - path: /etc/yum.repos.d/saltstack.repo
            owner: root:root
            permissions: '0444'
            content: |
              # installed by cloud-init
              [saltstack-repo]
              name=SaltStack repo for Red Hat Enterprise Linux $releasever
              baseurl=https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest
              enabled=1
              gpgcheck=1
              gpgkey=https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest/SALTSTACK-GPG-KEY.pub
                     https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest/base/RPM-GPG-KEY-CentOS-7
        packages: *cloud_config_packages
        runcmd:
          - [ systemctl, enable, salt-minion.service ]
          - [ systemctl, start, salt-minion.service ]
